services:
  mongodb:
    image: mongo:8.0.8
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=sq
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - mongo_net
      - monitoring_net

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - monitoring_net

  mongodb-exporter:
    image: percona/mongodb_exporter:0.40
    ports:
      - "9216:9216"
    command:
      - '--mongodb.uri=mongodb://admin:admin@mongodb:27017'
    networks:
      - monitoring_net
      - mongo_net
    depends_on:
      - mongodb

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - monitoring_net
    depends_on:
      - prometheus

volumes:
  mongodb:
  mongoconfig:
  prometheus_data:
  grafana_data:

networks:
  mongo_net:
    driver: bridge
  monitoring_net:
    driver: bridge
